name: CI

on:
  pull_request:
    branches:
      - master
      - release
    paths:
    - .github/workflows/ci.yml
    - FFMpegCore/**
    - FFMpegCore.Test/**

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    timeout-minutes: 6
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Prepare FFMpeg
      uses: Iamshankhadeep/setup-ffmpeg@v1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: "4.4"

    - name: Test with dotnet
      run: dotnet test FFMpegCore.sln --logger GitHubActions
